// admin-data.js — style metadata + sample channels
window.STYLES = [
  {
    id:'main', n:'01', label:'NEUTRAL',
    name:'Neutral · 工业橙',
    file:'/styles/main/',
    bg:'#FFFFFF', ink:'#0A0B0E', acc:'#C2410C',
    mood:'白底 + 工业橙 · 当前默认',
    audience:['通用','学生向'],
    feel:'明亮',
    summary:'最稳的版本。白底黑字 + 工业橙强调，文案密度适中，适合大多数学员第一次接触。',
  },
  {
    id:'v1', n:'02', label:'KRAFT',
    name:'Kraft · 牛皮纸',
    file:'/styles/v1/',
    bg:'#F4F1E9', ink:'#15171C', acc:'#C2410C',
    mood:'暖米底 + 工业橙 · 印刷质感',
    audience:['通用','文科向'],
    feel:'温润',
    summary:'像翻开一本工作手册。米色纸感底色削弱屏幕感，适合在朋友圈点开慢慢读的场景。',
  },
  {
    id:'v2', n:'03', label:'EDITORIAL',
    name:'Editorial · 财经版',
    file:'/styles/v2/',
    bg:'#F4F1EA', ink:'#0A0B0E', acc:'#B91C1C',
    mood:'象牙底 + 海军蓝 + 绯红 · FT 风格',
    audience:['商务向','管理者'],
    feel:'严肃',
    summary:'借鉴《金融时报》排版语言。适合发给在职、管理岗、对内容质感要求高的学员。',
  },
  {
    id:'v3', n:'04', label:'MONO',
    name:'Mono · 单色电光',
    file:'/styles/v3/',
    bg:'#FAFAFA', ink:'#0A0A0A', acc:'#7C3AED',
    mood:'纯白纯黑 + 电光紫 · Brutalist',
    audience:['设计向','极客'],
    feel:'锐利',
    summary:'极简到几乎只剩黑白。紫色作为唯一强调色出现。设计感强，给敏感人群。',
  },
  {
    id:'v4', n:'05', label:'SAGE',
    name:'Sage · 植物学',
    file:'/styles/v4/',
    bg:'#F3F2EC', ink:'#0A0B0E', acc:'#A6531C',
    mood:'鼠尾草 + 陶土赭 · 静谧自然',
    audience:['女性向','文科向'],
    feel:'柔和',
    summary:'低饱和、暖灰底 + 陶土赭。降焦虑、降攻击性，适合年龄稍长或对设计敏感的群体。',
  },
  {
    id:'v5', n:'06', label:'TERMINAL',
    name:'Terminal · 暗夜终端',
    file:'/styles/v5/',
    bg:'#0E1014', ink:'#EDE9DC', acc:'#F59E0B',
    mood:'深炭 + 琥珀 CRT · 工程师向',
    audience:['技术向','极客'],
    feel:'极客',
    summary:'CRT 显示器气质。深色底 + 琥珀色高亮 + 等宽字体，给程序员、运维、AI 工程师。',
  },
  {
    id:'v6', n:'07', label:'BUSINESS',
    name:'Business · 商务蓝',
    file:'/styles/v6/',
    bg:'#FFFFFF', ink:'#0A0B0E', acc:'#1D4ED8',
    mood:'白底 + 海军蓝 + 钴蓝 · 企业沟通',
    audience:['商务向','管理者'],
    feel:'稳重',
    summary:'传统企业页面气质。海军蓝主导，适合做 to-B 场景介绍或发给企业内部学员。',
  },
  {
    id:'v7', n:'08', label:'EDITORIAL+',
    name:'《卷·五》Editorial Folio',
    file:'/styles/v7/',
    bg:'#F4EFE5', ink:'#1A1611', acc:'#8B2A1F',
    mood:'★ 全新版面 · 杂志大开本，衬线 + 留白 + 编者按',
    audience:['通用','文科向'],
    feel:'高级',
    summary:'真正的杂志大开本。衬线主标题 + 编者按结构，发给读《新周刊》《三联》这类用户。',
    isNew:true,
  },
  {
    id:'v8', n:'09', label:'WHITEPAPER',
    name:'Technical Whitepaper',
    file:'/styles/v8/',
    bg:'#FAFAF6', ink:'#0A0907', acc:'#9C1F1F',
    mood:'★ 全新版面 · arXiv 技术报告，§ 编号 + 表格 + 脚注',
    audience:['技术向','极客'],
    feel:'学术',
    summary:'arXiv 论文的视觉语言。§ 编号、表格、脚注一应俱全。给科研、博士、技术管理者。',
    isNew:true,
  },
  {
    id:'v9', n:'10', label:'BENTO',
    name:'Bento Modular · 模块化卡片',
    file:'/styles/v9/',
    bg:'#EEEDE9', ink:'#0A0A0A', acc:'#FF5A1F',
    mood:'★ 全新版面 · 现代产品页，圆角大卡 + 强对比拼图',
    audience:['通用','设计向'],
    feel:'现代',
    summary:'现代产品页风格，类似 Apple 官网的拼图组合。年轻、视觉密度高、信息透气。',
    isNew:true,
  },
  {
    id:'v10', n:'11', label:'CLI',
    name:'CLI · 终端命令行',
    file:'/styles/v10/',
    bg:'#0B0E0A', ink:'#E8E2C7', acc:'#F0B23A',
    mood:'★ 全新版面 · 全终端风，等宽字体 + 琥珀 CRT + $ 提示',
    audience:['技术向','极客'],
    feel:'硬核',
    summary:'把整个落地页做成一个 shell 会话。$ 提示符、命令输出、ASCII 框，给硬核技术圈。',
    isNew:true,
  },
  {
    id:'v11', n:'12', label:'NEWSPAPER',
    name:'《冲刺日报》Newspaper',
    file:'/styles/v11/',
    bg:'#F4EFE3', ink:'#15110B', acc:'#9C1F1F',
    mood:'★ 全新版面 · 报纸头版，多栏 serif + masthead + 双线分隔',
    audience:['通用','文科向'],
    feel:'怀旧',
    summary:'报纸头版的视觉语言。多栏排版、报头花体、双线分隔。社交分享会很出彩。',
    isNew:true,
  },
  {
    id:'v12', n:'13', label:'BRUTALIST',
    name:'Brutalist · 极简极大字',
    file:'/styles/v12/',
    bg:'#F4F2EC', ink:'#0A0A0A', acc:'#E2FF40',
    mood:'★ 全新版面 · 极大字号 + 黑白 + 电光酸绿单色块',
    audience:['设计向','极客'],
    feel:'反叛',
    summary:'极简到极致——巨大字号 + 高对比 + 一抹荧光酸绿。给愿意尝鲜的设计师/创作者人群。',
    isNew:true,
  },
];

// 真实部署：SAMPLE_HISTORY 已弃用，本机历史从 localStorage 's5ch-history' 读
window.SAMPLE_HISTORY = [];

// fonts associated with each style (rough — for the preview card right rail)
window.STYLE_FONT_HINTS = {
  main:'Inter · 等宽 / 现代无衬线',
  v1:'Inter · 印刷质感',
  v2:'Serif Display · 财经风',
  v3:'Inter · Brutalist 极简',
  v4:'Serif · 自然柔和',
  v5:'JetBrains Mono · 终端',
  v6:'Inter · 商务',
  v7:'Serif Display · 编辑杂志',
  v8:'Serif · 学术报告',
  v9:'Sans · 现代产品',
  v10:'JetBrains Mono · CLI',
  v11:'Old Style Serif · 报纸',
  v12:'Sans Massive · Brutalist',
};
